<#
Temporarily enables the OpenSSH Server for a remote debug session, then
automatically disables it again after -DurationMinutes (default 60) via a
one-time Windows Scheduled Task - so access closes itself even if nobody
remembers to run Disable-SSHDebug.ps1, and even if the Syncro connection
drops mid-session.

Installs the OpenSSH.Server Windows capability if missing (left installed
afterwards - re-downloading it every session is wasteful and harmless to
leave present), starts sshd, sets it to Manual startup, and makes sure the
"OpenSSH-Server-In-TCP" firewall rule is enabled. That rule is not scoped to
a network profile by Windows (it applies on Domain/Private/Public alike), so
switching the connection profile to "Private" is not required for SSH itself
to work and this script does not touch it.

Original sshd startup type is captured once per session (in state.json) so
Disable-SSHDebug.ps1 can restore it exactly rather than assuming a default.
Re-running this script while a session is already active just extends the
timer (re-registers the scheduled task) without touching the saved state.

Deploys a local copy of Disable-SSHDebug.ps1 to
C:\ProgramData\ITFactory\SSHDebug\Disable-SSHDebug.ps1 for the scheduled
task to call - keep that embedded copy (below) in sync with the real
maintenance/Disable-SSHDebug.ps1 in this repo if you change one.

To disable immediately instead of waiting for the timer, run
Disable-SSHDebug.ps1 from Syncro.

Custom asset field (optional, Admin --> Custom Asset Fields):
  SSH Debug Expires   Text   yyyy-MM-dd HH:mm:ss
#>

param(
    [int]$DurationMinutes = 60
)

Import-Module $env:SyncroModule

$ErrorActionPreference = "Stop"

$stateDir           = "C:\ProgramData\ITFactory\SSHDebug"
$stateFile          = Join-Path $stateDir "state.json"
$localDisableScript = Join-Path $stateDir "Disable-SSHDebug.ps1"
$taskName           = "ITFactory-SSHDebug-AutoDisable"
$firewallRuleName   = "OpenSSH-Server-In-TCP"
$capabilityName     = "OpenSSH.Server~~~~0.0.1.0"

try {
    New-Item -ItemType Directory -Path $stateDir -Force | Out-Null

    # --- Install OpenSSH Server capability if missing ---
    $capability = Get-WindowsCapability -Online -Name $capabilityName
    if ($capability.State -ne "Installed") {
        Write-Host "Installiere OpenSSH-Server-Feature..."
        Add-WindowsCapability -Online -Name $capabilityName | Out-Null
    }

    $service = Get-Service -Name sshd

    # --- Capture original state only on first enable of a session ---
    if (-not (Test-Path $stateFile)) {
        $state = @{
            OriginalStartType = $service.StartType.ToString()
            EnabledAt         = (Get-Date).ToString("s")
        }
        $state | ConvertTo-Json | Set-Content -Path $stateFile -Encoding UTF8
        Write-Host "Ausgangszustand gesichert: sshd StartType war '$($state.OriginalStartType)'."
    } else {
        Write-Host "SSH-Debug-Session bereits aktiv - Timer wird verlaengert."
    }

    # --- Start sshd ---
    Set-Service -Name sshd -StartupType Manual
    if ($service.Status -ne "Running") {
        Start-Service -Name sshd
    }

    # --- Ensure the firewall rule is enabled ---
    $rule = Get-NetFirewallRule -Name $firewallRuleName -ErrorAction SilentlyContinue
    if ($rule) {
        Set-NetFirewallRule -Name $firewallRuleName -Enabled True
    } else {
        New-NetFirewallRule -Name $firewallRuleName -DisplayName "OpenSSH SSH Server (sshd)" `
            -Direction Inbound -Protocol TCP -LocalPort 22 -Action Allow | Out-Null
    }

    # --- Deploy the local copy of the disable logic the scheduled task will call ---
    # Keep this in sync with maintenance/Disable-SSHDebug.ps1 in the repo.
    @'
<# Auto-generated by Enable-SSHDebug.ps1 - do not edit here, edit maintenance/Disable-SSHDebug.ps1 in the repo instead and re-run Enable-SSHDebug.ps1 to redeploy. #>
Import-Module $env:SyncroModule

$stateDir         = "C:\ProgramData\ITFactory\SSHDebug"
$stateFile        = Join-Path $stateDir "state.json"
$taskName         = "ITFactory-SSHDebug-AutoDisable"
$firewallRuleName = "OpenSSH-Server-In-TCP"

$originalStartType = "Disabled"
if (Test-Path $stateFile) {
    try { $originalStartType = (Get-Content $stateFile -Raw | ConvertFrom-Json).OriginalStartType } catch {}
}

$service = Get-Service -Name sshd -ErrorAction SilentlyContinue
if ($service) {
    Stop-Service -Name sshd -Force -ErrorAction SilentlyContinue
    Set-Service -Name sshd -StartupType $originalStartType -ErrorAction SilentlyContinue
}

Set-NetFirewallRule -Name $firewallRuleName -Enabled False -ErrorAction SilentlyContinue

Unregister-ScheduledTask -TaskName $taskName -Confirm:$false -ErrorAction SilentlyContinue
Remove-Item $stateFile -ErrorAction SilentlyContinue

$msg = "OpenSSH-Debug-Zugriff auf $env:COMPUTERNAME wurde automatisch deaktiviert (sshd StartType zurueckgesetzt auf '$originalStartType')."
Write-Host $msg
Rmm-Alert -Category "SSH Debug Access" -Body $msg
'@ | Set-Content -Path $localDisableScript -Encoding UTF8

    # --- (Re-)register the one-time auto-disable task ---
    Unregister-ScheduledTask -TaskName $taskName -Confirm:$false -ErrorAction SilentlyContinue

    $action    = New-ScheduledTaskAction -Execute "powershell.exe" `
        -Argument "-WindowStyle Hidden -NoProfile -ExecutionPolicy Bypass -File `"$localDisableScript`""
    $expiresAt = (Get-Date).AddMinutes($DurationMinutes)
    $trigger   = New-ScheduledTaskTrigger -Once -At $expiresAt
    $principal = New-ScheduledTaskPrincipal -UserId "SYSTEM" -LogonType ServiceAccount -RunLevel Highest
    $settings  = New-ScheduledTaskSettingsSet -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries -StartWhenAvailable -Hidden

    Register-ScheduledTask -TaskName $taskName -Action $action -Trigger $trigger `
        -Principal $principal -Settings $settings -Force | Out-Null

    try { Set-Asset-Field -Name "SSH Debug Expires" -Value $expiresAt.ToString("yyyy-MM-dd HH:mm:ss") } catch {}

    $ips = (Get-NetIPAddress -AddressFamily IPv4 | Where-Object { $_.InterfaceAlias -notmatch "Loopback" }).IPAddress -join ", "

    $msg = "OpenSSH-Debug-Zugriff auf $env:COMPUTERNAME aktiviert bis $($expiresAt.ToString('yyyy-MM-dd HH:mm:ss')). IP(s): $ips"
    Write-Host $msg
    Write-Host "Verbindung: ssh <user>@<ip>"
    Rmm-Alert -Category "SSH Debug Access" -Body $msg

    exit 0
}
catch {
    $msg = "Aktivieren von OpenSSH-Debug fehlgeschlagen: $($_.Exception.Message)"
    Write-Host "ERROR: $msg"
    Rmm-Alert -Category "SSH Debug Access" -Body $msg
    exit 1
}
